#!/bin/bash
#
echo -n "sisesta kuu number"
read kuu
if test $kuu -gt 0 -a $kuu -lt 3
then 
echo "Talv"
elif test $kuu -ge 3 -a $kuu -lt 6
then
echo "kevad"
elif test $kuu -ge 6 -a $kuu -lt 9
then
echo "suvi"
elif test $kuu -ge 9 -a $kuu -lt 12
then
echo "sügis"
else 
echo "vigane sisend"
fi
#
