#!/bin/bash
#
echo -n "Sisesta kellaaeg"
read kell
if test $kell -ge 6  -a $kell -lt 12
then
echo "Tere Hommikust!"
elif [ $kell -ge 12 -a $kell -lt 18 ];then
echo "Tere päevast"
elif [ $kell -ge 18 -a $kell -lt 22 ]
then
echo "Tere õhtust"
elif [ $kell -ge 22 -a $kell -lt 24 ]
then
echo "Head ööd"
elif [ $kell -ge 0 -a $kell -lt 6 ]
then
echo "Head ööd"
else
echo "Vigane sisend"
fi
#

