#!/bin/bash
#
kell=`date | cut -c12-13`
#
if test $kell -gt 6 -a $kell -lt 12
then
echo "Tere hommikust, $USER!"
elif test $kell -ge 12 -a $kell -lt 18
then
echo "Tere päevast, $USER!"
elif test $kell -ge 18 -a $kell -lt 22
then
echo "Head ööd, $USER!"
elif test $kell -ge 22 -a $kell -lt 24
then
echo "head ööd, $USER"
elif test $kell -ge 0 -a $kell -lt 6
then
echo "head ööd, $USER"
else
echo "vigane sisend"
fi
#

